### ISSUE TITLE
support for Java

### ISSUE THREAD

**Issue by kantbinh** [GetStream/avatarview-android#19]
Is the library support for Java? If yes, can you include a sample for java using. Thank you so much for this awesome lib.

**Comment by skydoves** [comment]
Hi @nguyencongbinh! 
Unfortunately, there's no plan to support Java for now. The  `AvatarView` already uses Coroutines internally. Also, Coil is an image loading for Android backed by Kotlin Coroutines. If we have any plans for Java, I'll let you know. Thank you!
