### ISSUE TITLE
Getting initial image drawable

### ISSUE THREAD

**Issue by timplifier** [GetStream/avatarview-android#39]
I was trying to get the drawable of the initial image in order to download it to local storage, however, it is not possible now. I was using this piece of code
`avatarView.drawable.toBitmap()`
it throws null pointer exception, stating that drawable is null all the time.

**Comment by skydoves** [comment]
Hi @Clar1fy, for now, we don't have support providing image drawable of the `AvatarView`.
Instead, check out this - https://stackoverflow.com/questions/3107527/android-save-view-to-jpg-or-png
Thanks!

**Comment by timplifier** [comment]
Thanks
